### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by ghostdogtm** [TurBoss/TurBoHockeyEditor3000#1]
My friend has a bug with UI on windows 7 classic style theme. May you suggest something?
![hock_etdr](https://cloud.githubusercontent.com/assets/15708129/22264635/67b977fc-e281-11e6-9a31-89da08b45211.PNG)

**Comment by TurBoss** [comment]
sorry for the delay I didn't notice about this in years

i saw you have made your own editor, I hope the soruce here was useful for you

this app was made with boaconstructor in windows ZP  I'll try to build it for win 7 +

**Comment by TurBoss** [comment]
https://github.com/TurBoss/TurBoHockeyEditor3000/releases/tag/0.1-win7

Thnak you !

**Comment by TurBoss** [comment]
![imagen](https://user-images.githubusercontent.com/184088/68517320-65cd1100-0287-11ea-9a19-ec33c78960fa.png)
